wip

diff --git a/docker/Dockerfile.isaaclab_arena b/docker/Dockerfile.isaaclab_arena
--- a/docker/Dockerfile.isaaclab_arena
+++ b/docker/Dockerfile.isaaclab_arena
@@ -52,8 +52,25 @@ RUN ${ISAACLAB_PATH}/isaaclab.sh -i
 # Install Isaac Teleop Python APIs (retargeters, device I/O, OpenXR bindings)
 RUN /isaac-sim/python.sh -m pip install isaacteleop~=1.1.0 --extra-index-url https://pypi.nvidia.com
 
-# Upgrade pip ahead of the editable install
-RUN /isaac-sim/python.sh -m pip install --upgrade pip
+# Install pip dependencies
+# NOTE(alexmillane, 2025-07-22): Dependencies are installed in the IsaacSim version of python.
+RUN /isaac-sim/python.sh -m pip install --upgrade pip && \
+  /isaac-sim/python.sh -m pip install \
+  pytest \
+  jupyter \
+  # NOTE(xinjieyao, 2025-09-15): Needed for inheritance of torch nn.module, saving/loading model
+  typing_extensions \
+  # NOTE(xinjieyao, 2025-09-15): Needed for WBC running onnx compiled policy
+  onnxruntime
+
+RUN rm -rf /isaac-sim/exts/omni.isaac.ml_archive/pip_prebundle/typing_extensions*
+RUN rm -rf /isaac-sim/exts/omni.pip.cloud/pip_prebundle/typing_extensions*
+
+# lwlabs deps
+RUN /isaac-sim/python.sh -m pip install --upgrade pip && \
+  /isaac-sim/python.sh -m pip install \
+  vuer[all] \
+  lightwheel-sdk
 
 # Lightwheel server
 ENV LW_API_ENDPOINT="https://api-dev.lightwheel.net"
@@ -75,13 +92,15 @@ COPY docker/setup/install_cuda.sh /tmp/install_cuda.sh
 RUN chmod +x /tmp/install_cuda.sh
 
 RUN if [ "$INSTALL_CUROBO" = "true" ]; then \
-    /tmp/install_cuda.sh && \
-    export TORCH_CUDA_ARCH_LIST=8.0+PTX && \
-    /isaac-sim/python.sh -m pip install --no-build-isolation \
-    "nvidia-curobo @ git+https://github.com/NVlabs/curobo.git@ebb71702f3f70e767f40fd8e050674af0288abe8" && \
-    /isaac-sim/python.sh -m pip install rerun-sdk==0.23; \
+      /tmp/install_cuda.sh && \
+      export TORCH_CUDA_ARCH_LIST=8.0+PTX && \
+      /isaac-sim/python.sh -m pip install --no-build-isolation \
+      "nvidia-curobo @ git+https://github.com/NVlabs/curobo.git@ebb71702f3f70e767f40fd8e050674af0288abe8" && \
+      /isaac-sim/python.sh -m pip install rerun-sdk==0.23 && \
+      /isaac-sim/python.sh -m pip install "packaging<24" && \
+      /isaac-sim/python.sh -m pip show nvidia-curobo || (echo "ERROR: nvidia-curobo install failed"; exit 1); \
     else \
-    echo "Skipping cuRobo installation"; \
+      echo "Skipping cuRobo installation"; \
   fi
 
 # If GR00T deps to be installed, install cuda 12.8 (needed for flash-attn, and avoid 4G memory addon)
@@ -119,6 +138,7 @@ RUN /isaac-sim/python.sh -m pip install -e "${WORKDIR}/[dev]"
 RUN echo "alias python='/isaac-sim/python.sh'" >> /etc/bash.bashrc
 RUN echo "alias pip3='/isaac-sim/python.sh -m pip'" >> /etc/bash.bashrc
 RUN echo "alias pytest='/isaac-sim/python.sh -m pytest'" >> /etc/bash.bashrc
+RUN echo "export PATH=/isaac-sim/kit/python/bin:\$PATH" >> /etc/bash.bashrc
 
 # Debugging with debugpy (installed via setup.py[dev])
 # Usage:
